config/routes.rb
Rails.application.routes.draw do
   
  
   resources :posts do
    resources :comments 
  end

  resources :users , :attaches, only: [:index, :new, :create, :destroy,:show,:update,:edit] 
  resources :groups ,:usergroups ,only:[:new,:create,:destroy,:index,:update,:show]
  root to:'posts#index'

  get 'groups/new' => "groups#new"
  post 'groups/create'=>"groups#create"
  get 'groups/index'=>"groups/index"

  get 'users/new' => "users#new"
  post 'users/create'=> "users#create"
  get '/login' =>"sessions#new"
  post '/login'=>"sessions#create"
  get '/logout' =>"sessions#destroy"

  get 'usergroups/update'=>"usergroups#update"
  put 'usergroups/:id' =>"usergroups#update"
  
  get 'attaches/new'=>"attaches#new"
  post 'attaches/create'=>"attaches#create"

  get 'users/:id' => "users#show"
  get 'attaches/:id '=> 'attaches#show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attach.rb
class Attach < ApplicationRecord
	belongs_to :user 
	mount_uploader :attachment, AttachmentUploader
	mount_uploader :attachment1, AttachmentUploader
	mount_uploader :attachment2, AttachmentUploader
	mount_uploader :attachment3, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :attachment, :name, presence: true 
end

app/controllers/attaches_controller.rb
class AttachesController < ApplicationController
 
  def new
    @attach=current_user.attaches.build
  end

  def create
    @attach=current_user.attaches.build(attaches_params)
    if @attach.save
      redirect_to attach_url(@attach)
    else
      render :new
    end
  end


  def destroy
  end

  def update
    @attach=Attach.find(params[:id])
    @attach.update(attaches_params)
    redirect_to attach_url
  end

  def show
    @attach=Attach.find(params[:id])
  end

  def index
    @attaches=Attach.all
  end

  def edit
    @attach=Attach.find(params[:id])
  end

end

private
def attaches_params
  params.require(:attach).permit(:name,:attachment,:attachment1,:attachment2,:attachment3,:name1,:name2,:name3)
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/views/attaches/_attach.html.erb
<h1>The files</h1>
 <table class="table table-hover">
 	<thead>
 		<tr>
 			<th>Name</th>
 			<th>Info</th>
 			<th colspan="2"></th>
 		</tr>
 	</thead>
 	<tbody>
 		<tr>
 			<td> <%= @attach.name %></td>
 			<td><%= link_to "Download file", @attach.attachment_url, class:'btn btn-success' %></td>
 		</tr>
 		<tr>
 			<td> <%= @attach.name1 %></td>
 			<td><%= link_to "Download file", @attach.attachment1_url, class:'btn btn-success' %></td>
 		</tr>
 		<tr>
 			<td> <%= @attach.name2 %></td>
 			<td><%= link_to "Download file", @attach.attachment2_url, class:'btn btn-success' %></td>
 		</tr>
 		<tr>
 			<td> <%= @attach.name3 %></td>
 			<td><%= link_to "Download file", @attach.attachment3_url, class:'btn btn-success' %></td>
 		</tr>
 	</tbody>
 </table>
  
   

app/views/attaches/_form.html.erb
<% provide(:title, "Profile") %>
<% if @attach.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @attach.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
     
   </div>
  <% end %>
<div class = "file">
   <%= form_for @attach, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <br>
      <%= f.label :name1 %>
      <%= f.text_field :name1 %>
      <br>
      <%= f.label :attachment1 %>
      <%= f.file_field :attachment1 %>
      <br>
      <%= f.label :name2 %>
      <%= f.text_field :name2 %>
      <br>
      <%= f.label :attachment2 %>
      <%= f.file_field :attachment2 %>
      <br>
      <%= f.label :name3 %>
      <%= f.text_field :name3 %>
      <br>
      <%= f.label :attachment3 %>
      <%= f.file_field :attachment3 %>
      <br>
      <%= f.submit "Save", class: "btn btn-primary" %>
   
   <% end %>

</div>

app/views/attaches/edit.html.erb
<% provide(:title, "profile") %>
<div class="profile">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-6 col-sm-6">
        
      <%= render 'form' , attach: @attach  %>

      </div>
    </div>
  </div>
</div>

app/views/attaches/index.html.erb
<%= will_paginate @users %>
<div class="profile">
<h1>The files</h1>
  <%=@attaches.each do |attach| %>
  <%= attach.name %><br>
  <%= link_to "Download file", attach.attachment_url %> 		
  <%  end -%>
 </div>
 <%= will_paginate @users %>

app/views/attaches/new.html.erb
<% provide(:title, "profile") %>
<div class="profile">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-6 col-sm-6">
        
      <%= render 'attaches/form' %>

      
      </div>
    </div>
  </div>
</div>

app/views/attaches/show.html.erb
<% provide(:title, "profile") %>
<div class="files">
<div class="container">
<div class="row">
<div class="col-md-6 col-xs-6 col-sm-12">

<% if current_user && current_user.student? %>

 <%= render @attach %>
 <p>&nbsp;</p>
 <%= link_to 'Edit' , edit_attach_path(@attach) , class:'btn btn-warning' %>
 <p>&nbsp;</p>
 <%= render 'form', attach: @attach %><br>

   

<% elsif current_user && current_user.staff? %>
  <u><h4><strong>Files</strong></h4></u>
  <%= render @attach %>

     <p>&nbsp;</p>
	 <p>&nbsp;</p>
 <% end %>
</div>
</div>
</div>
</div>

app/views/attaches/update.html.erb
<h1>Attaches#update</h1>
<p>Find me in app/views/attaches/update.html.erb</p>