config/routes.rb
Rails.application.routes.draw do
   
  
   resources :posts do
    resources :comments 
  end

  resources :users , :attaches, only: [:index, :new, :create, :destroy,:show,:update,:edit] 
  resources :groups ,:usergroups ,only:[:new,:create,:destroy,:index,:update,:show]
  root to:'posts#index'

  get 'groups/new' => "groups#new"
  post 'groups/create'=>"groups#create"
  get 'groups/index'=>"groups/index"

  get 'users/new' => "users#new"
  post 'users/create'=> "users#create"
  get '/login' =>"sessions#new"
  post '/login'=>"sessions#create"
  get '/logout' =>"sessions#destroy"

  get 'usergroups/update'=>"usergroups#update"
  put 'usergroups/:id' =>"usergroups#update"
  
  get 'attaches/new'=>"attaches#new"
  post 'attaches/create'=>"attaches#create"

  get 'users/:id' => "users#show"
  get 'attaches/:id '=> 'attaches#show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_groups
	has_many :groups, through: :user_groups
	has_many :posts    , dependent: :destroy
    has_many :attaches , dependent: :destroy
    validates :name , presence: true
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ 
    validates :email , uniqueness: true , on: :create
    validates :name , uniqueness: true , on: :create
    validates :password , :length => { :minimum=>6 } 

	 def staff? 
	  self.role == 'staff' 
	end

	def student? 
	  self.role == 'student' 
	end
	
	def admin? 
	  self.role == 'admin' 
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only:[:show,:index]
  def index
    @posts=Post.all
    @users=User.all.paginate(page: params[:page],per_page: 5)

  end

  def show
    @user=User.find(params[:id])
    @posts=@user.posts    
    @attaches=@user.attaches
  end

  def create
    @group=Group.new
    @user=User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      render :new
    end

  end

  def destroy
     @user=User.find(params[:id])
     @user.destroy
     redirect_to users_url
  end

  def update
   @user.update(status: params[:status])
    redirect_to :back, notice: 'Successfully updated'
  end

  def new
    @user=User.new
    @group=Group.new
  end
end
private
def user_params
  params.require(:user).permit(:name,:role,:email,:password,:user_id,:group_id,:status)
end

app/helpers/users_helper.rb
module UsersHelper
	def build_read_status_link user
		if user.status == true 
			link_to 'Un-valid', post_path(@post, status: false), method: :put
		else
			link_to 'valid', post_path(@post, status: true), method: :put
		end
	end
end

app/views/users/_user.html.erb
 <p>
  <strong>User:</strong>
  <%= @post.user.name %>
  <nav class="nav pull-right">
  	<%= status_converter(@post.user.status, truthy: 'validated', falsey: 'not-validate') %><br>
  </nav>
</p>
<% if current_user && current_user.staff? %> 
<p>
	<%= build_read_status_link user%>
</p> 
<%  end -%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<% provide(:title, "users") %>
<div class="uindex">
<div class="row">
<div class="container">
<div class="col-md-9 col-xs-9 col-sm-12">
<div class="nav navbar-nav">
<br><br>

<p id="notice"><%= notice %></p>



<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td width="25%"><%=link_to user.name , '#' ,class:'navbar-header' %></td>
        <td width="25%"><%=link_to user.role, '#' ,class:'navbar-header' %></td>
        <td width="50%"><%=link_to user.email, '#' ,class:'navbar-header' %></td>
        <td>
        <% if current_user && current_user.staff? %> 
    
          <%= link_to  "+ Add", '#' ,class: "btn btn-success pull-right join-button" %> 
        </td>
   		<% end %>
      </tr>
    <% end %>
 </tbody>
 </table>


 </div>
 </div>
 </div>
 </div>

<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, "sign up") %>
<div class="signup">
<div class="row">
<div class="container">
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
 <% end -%>
<div class="col-md-6 col-xs-6 col-sm-12">
 <%= form_for @user, url:{action: "create" } do |f| %>
       
       <p class="danger">*choose unique user name</p>
      <%= f.text_field :name , placeholder:'name' %>
      
       <%= f.select :role, options_for_select([['student', 'student'], ['staff', 'staff'], ['admin', 'admin']] , selected: :role ) %>
       <p class="danger">*choose unique email</p>
       <%= f.email_field :email,placeholder:'Email' %>

       <p class="danger">*password minimum length six</p>
       <%= f.password_field :password, placeholder:'password' %>

      <%= f.submit "create", :class => "btn" %>
  <% end %> 
  </div>
  </div>
  </div>
  </div>  

app/views/users/show.html.erb
<div class="profile">
<div class="col-md-6 col-xs-6 col-sm-6">
	<%= current_user.name %> <hr>
    <%= current_user.email %><hr>
    
</div>
</div>

app/views/users/update.html.erb
=begin
<%= form_for @user, {:url=>usergroup_path(@user), method: :post do |f| %>
<%= f.hidden_field :user_id, :value=>current_user.id %>
<%= f.hidden_field :group_id, :value=>group.id %>
<%= submit_tag "+Join", :class => "btn btn-primary pull-right join-button" %>
<% end %>
=end