config/routes.rb
Rails.application.routes.draw do
   
  
   resources :posts do
    resources :comments 
  end

  resources :users , :attaches, only: [:index, :new, :create, :destroy,:show,:update,:edit] 
  resources :groups ,:usergroups ,only:[:new,:create,:destroy,:index,:update,:show]
  root to:'posts#index'

  get 'groups/new' => "groups#new"
  post 'groups/create'=>"groups#create"
  get 'groups/index'=>"groups/index"

  get 'users/new' => "users#new"
  post 'users/create'=> "users#create"
  get '/login' =>"sessions#new"
  post '/login'=>"sessions#create"
  get '/logout' =>"sessions#destroy"

  get 'usergroups/update'=>"usergroups#update"
  put 'usergroups/:id' =>"usergroups#update"
  
  get 'attaches/new'=>"attaches#new"
  post 'attaches/create'=>"attaches#create"

  get 'users/:id' => "users#show"
  get 'attaches/:id '=> 'attaches#show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :statues
	has_many :comments
	belongs_to :user, optional: true
	validates :user_id , presence: true , allow_nil: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only:[:show,:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page],per_page: 3)
    @users=User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post=Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @post=Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post=Post.find(params[:id])
    respond_to do |format|
      if @post.update(status: params[:status])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :domain, :content, :status)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def status_weight post
		post.status == false ?  'font-color:red' : 'font-color:green'
	end
	def build_read_status_link post
		if post.status == true 
			link_to 'Un-valid', post_path(post, status: false), method: :put
		else
			link_to 'valid', post_path(post, status: true), method: :put
		end
	end
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :domain %>
    <%= f.text_field :domain %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="profile">
<div class="container">
<div class="row">
<div class="col-md-6 col-sm-6 col-xs-6">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</div>
</div>
</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<div class="profile">
<div class="container">
<div class="row">
<div class="col-md-9 col-sm-12 col-xs-9">

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Domain</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.domain %></td>
        <td><%= truncate(post.content,:length=>20) %>
        </td>
       <td> 
       <td> <%= link_to 'Show', post , class:'btn btn-success' %></td>
       <% if current_user == post.user && current_user.staff? %>
        <%= link_to 'Show', post , class:'btn btn-success' %></td>
        
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-danger'%></td>
      
         
        
         <% elsif current_user == post.user && current_user.student? %>
        <td><%= link_to 'Edit', edit_post_path(post), class:'btn btn-warning' %></td>
         <% end %>
      </tr>
    <% end %>
   
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path,class:'btn btn-info' %>

</div>
</div>
</div>


<%= will_paginate @posts %>

<br><br>


</div>

app/views/posts/new.html.erb
<div class="profile_new">
<div class="container">
<div class="row">
<div class="col-md-6 col-sm-6 col-xs-6">

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

</div>
</div>
</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Profile") %>
<div class="profile">
<div class="container">
<div class="row">
<div class="col-md-6 col-sm-12 col-xs-6">

<p id="notice"><%= notice %></p>



<p  style=<%=status_weight(@post) %>>
  <strong>User:</strong>
  <%= @post.user.name %>
  
  <%= status_converter(@post.status, truthy: 'validated', falsey: 'not-validated') %><br><br>
  
  <% if current_user.staff? %>
  <%= build_read_status_link @post %>
  <%  end -%>
</p>
<hr>


<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<hr>


<p>
  <strong>Domain:</strong>
  <%= @post.domain %>
</p>
<hr>


<p class="text-justify" >
   <div class="container">
   <div class="col-md-6">
   <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo">Toggle here to read the content +</button>
 <div id="demo" class="collapse"> 
   <%= @post.content %><br><br>
  </div>
</div>
</div>
  </p>
<hr>


<% if current_user==@post.user || current_user.staff? %>
<p>
  
  <%= link_to 'view_files' , attach_url %>
</p>
<hr>

<%= link_to 'Edit', edit_post_path(@post) %> 
<u><h4><strong>Comments</strong></h4></u>
<%= render @post.comments %>
<%  end -%>
<%= link_to 'Back', posts_path %>
 <p>&nbsp;</p>
<p>&nbsp;</p>
<% if current_user && current_user.staff? %>
<u><h5><strong>Add a comment:</strong></h5></u>
<%= render 'comments/form' %>
 <p>&nbsp;</p>
<% end %>
</div>
</div>
</div>
</div>