config/routes.rb
Rails.application.routes.draw do
   
  
   resources :posts do
    resources :comments 
  end

  resources :users , :attaches, only: [:index, :new, :create, :destroy,:show,:update,:edit] 
  resources :groups ,:usergroups ,only:[:new,:create,:destroy,:index,:update,:show]
  root to:'posts#index'

  get 'groups/new' => "groups#new"
  post 'groups/create'=>"groups#create"
  get 'groups/index'=>"groups/index"

  get 'users/new' => "users#new"
  post 'users/create'=> "users#create"
  get '/login' =>"sessions#new"
  post '/login'=>"sessions#create"
  get '/logout' =>"sessions#destroy"

  get 'usergroups/update'=>"usergroups#update"
  put 'usergroups/:id' =>"usergroups#update"
  
  get 'attaches/new'=>"attaches#new"
  post 'attaches/create'=>"attaches#create"

  get 'users/:id' => "users#show"
  get 'attaches/:id '=> 'attaches#show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attach.rb
class Attach < ApplicationRecord
	belongs_to :user 
	mount_uploader :attachment, AttachmentUploader
	mount_uploader :attachment1, AttachmentUploader
	mount_uploader :attachment2, AttachmentUploader
	mount_uploader :attachment3, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :attachment, :name, presence: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
	 belongs_to :post 
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups
	has_many :users , through: :user_groups
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :statues
	has_many :comments
	belongs_to :user, optional: true
	validates :user_id , presence: true , allow_nil: true
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_groups
	has_many :groups, through: :user_groups
	has_many :posts    , dependent: :destroy
    has_many :attaches , dependent: :destroy
    validates :name , presence: true
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ 
    validates :email , uniqueness: true , on: :create
    validates :name , uniqueness: true , on: :create
    validates :password , :length => { :minimum=>6 } 

	 def staff? 
	  self.role == 'staff' 
	end

	def student? 
	  self.role == 'student' 
	end
	
	def admin? 
	  self.role == 'admin' 
	end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups=Group.all
    @users=User.new
  end

  def show
  end

  def create
    @group=current_user.groups.build(group_params)  
    if @group.save
      redirect_to '/'
    else
      render :new
    end
  end

  def destroy
  end

  def update
   
  end

  def new
    @group=current_user.groups.build
  end
end

private
def group_params
  params.require(:group).permit(:user_id,:group_id)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only:[:show,:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page],per_page: 3)
    @users=User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post=Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @post=Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post=Post.find(params[:id])
    respond_to do |format|
      if @post.update(status: params[:status])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :domain, :content, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only:[:show,:index]
  def index
    @posts=Post.all
    @users=User.all.paginate(page: params[:page],per_page: 5)

  end

  def show
    @user=User.find(params[:id])
    @posts=@user.posts    
    @attaches=@user.attaches
  end

  def create
    @group=Group.new
    @user=User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      render :new
    end

  end

  def destroy
     @user=User.find(params[:id])
     @user.destroy
     redirect_to users_url
  end

  def update
   @user.update(status: params[:status])
    redirect_to :back, notice: 'Successfully updated'
  end

  def new
    @user=User.new
    @group=Group.new
  end
end
private
def user_params
  params.require(:user).permit(:name,:role,:email,:password,:user_id,:group_id,:status)
end

app/helpers/application_helper.rb
module ApplicationHelper
	def status_converter(status, truthy: 'Active', falsey: 'Pending')
		if status
			truthy
		else
			falsey
		end
	end

	def full_title(page_title = '')
    base_title = "centralize"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def status_weight post
		post.status == false ?  'font-color:red' : 'font-color:green'
	end
	def build_read_status_link post
		if post.status == true 
			link_to 'Un-valid', post_path(post, status: false), method: :put
		else
			link_to 'valid', post_path(post, status: true), method: :put
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statues_helper.rb
module StatuesHelper

	def build_read_status_link post
		if post.status == true 
			link_to 'Un-valid', status_path(status, status: false), method: :put
		else
			link_to 'valid', status_path(status, status: true), method: :put
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def build_read_status_link user
		if user.status == true 
			link_to 'Un-valid', post_path(@post, status: false), method: :put
		else
			link_to 'valid', post_path(@post, status: true), method: :put
		end
	end
end

app/helpers/usersgroups_helper.rb
module UsersgroupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
    
    </style>
   <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
      
  </head>

  <body>

      <nav class="navbar navbar-inverse navbar-fixed-top">
       <div class="container-fluid">
        <div class="navbar-header">
         
          <% if current_user && current_user.staff? %> 
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ex">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>

           <%= link_to 'Centralize System' ,root_url , class:"navbar-brand active" %>

        </div>

        <div class="collapse navbar-collapse" id="ex">
        <ul class="nav navbar-nav navbar-right">
        <%= link_to 'post_index', posts_path %>
        <%= link_to 'group_index', groups_index_path %>
        <%= link_to 'users_index', users_path %>
           <br>
           <div class="dropdown">
           <br>
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"> 
            <%= current_user.email %>
            <span class="caret"></span></button>
            <section class="dropdown-menu">
            <%= link_to 'create_group', groups_new_path %>
            <%= link_to 'log out', logout_path %>
             </section>
            </div>        
        </ul>
        </div>
    
    <% elsif current_user && current_user.student? %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ex">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
           </button>
           <%= link_to 'Centralize System' ,root_url , class:"navbar-brand"  %>
        </div>

        <div class="collapse navbar-collapse" id="ex">
        <ul class="nav navbar-nav navbar-right">
        <br>
        <%= link_to 'users_index', users_path  %>
        <%= link_to 'posts' , posts_path   %>
        <div class="dropdown">
        <br>
        <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown" > 

       My profile
       <span class="caret"></span></button>
       <section class="dropdown-menu">
       <%= link_to current_user.email, current_user %><br>
       <%= link_to 'Attach_files',  new_attach_path %><br>
       <%= link_to 'Create_post',  new_post_path%><br>
       <%= link_to 'Attach_files' , new_attach_path %><br>
       <%= link_to 'log out', logout_path %>
       </section>
       </div>
       
       </ul>
       </div>
        
    <% elsif current_user %>
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ex">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
           </button>
           <%= link_to 'Centralize System' ,root_url , class:"navbar-brand", class:"active" %>
        </div>
         <div class="collapse navbar-collapse" id="ex">
        <ul class="nav navbar-nav pull-right">
       <%= link_to 'post_index', user_posts_path %>
       <%= link_to 'users_index', users_path %>
       <%= link_to 'log out',logout_path%>
       <%= current_user.email %>
     </ul>
     </div>

    <% else %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ex">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
           </button>
           <%= link_to 'Centralize System' ,root_url , class:"navbar-brand" %>
        </div>
       <div class="collapse navbar-collapse" id="ex">
        <ul class="nav navbar-nav navbar-right">
        <br>
       <%= link_to 'log in', login_path  %>
       <%= link_to 'sign up', new_user_path %>
     <% end %>
     </ul>
     </div>
</nav>
</div>

    <br/>
    <br/>

    <div class="myprofile">
    <% if current_user && current_user.student? %>
    <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown" > 
        My profile
       <span class="caret"></span></button>
       <section class="dropdown-menu">
       <%= link_to current_user.email, current_user %><br>
       <%= link_to 'Attach_files',  new_attach_path %><br>
       <%= link_to 'Create_post',  new_post_path%><br>
       <%= link_to 'Attach_files' , new_attach_path %><br>
       <%= link_to 'log out', logout_path %>

    <% end %>

    </section>
    </div>
    <%= yield %>
  </body>
</html>